name: Release

on:
  push:
    tags:
      - v*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin
      - name: Test
        run: cargo test --release
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: make dmg-universal
      - name: Rename files
        run: |
          mv ./target/release/osx/Alacritty.dmg ./Alacritty-${GITHUB_REF##*/}.dmg
      - uses: svenstaro/upload-release-action@v2
        name: Upload attachment to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Alacritty-${GITHUB_REF##*/}.dmg
          tag: ${{ github.ref }}
          overwrite: true

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        run: |
          cp ./target/release/alacritty.exe ./Alacritty-${GITHUB_REF##*/}-portable.exe
          ./.github/workflows/upload_asset.sh \
            ./Alacritty-${GITHUB_REF##*/}-portable.exe $GITHUB_TOKEN
      - name: Install WiX
        run: nuget install WiX
      - name: Download and unpack OpenConsole bundle
        run: |
          wget https://github.com/DoomHammer/openconsole-bundle/releases/download/v0.1/openconsole-bundle.zip
          unzip x openconsole-bundle.zip
      - name: Crate msi installer
        run: |
          ./WiX.*/tools/candle.exe -nologo -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./alacritty.wixobj" "extra/windows/wix/alacritty.wxs"
          ./WiX.*/tools/light.exe -nologo -ext WixUIExtension -ext WixUtilExtension \
            -out "./Alacritty-${GITHUB_REF##*/}-installer.msi" -sice:ICE61 -sice:ICE91 \
            "./alacritty.wixobj"
      - name: Upload msi installer
        run: |
          ./.github/workflows/upload_asset.sh \
            ./Alacritty-${GITHUB_REF##*/}-installer.msi $GITHUB_TOKEN
      - uses: svenstaro/upload-release-action@v2
        name: Upload attachment to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Alacritty-${GITHUB_REF##*/}-installer.msi
          tag: ${{ github.ref }}
          overwrite: true

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev \
            libxcb-xfixes0-dev libxkbcommon-dev python3
      - name: Test
        run: cargo test --release
      - name: Gzip manpage
        run: |
          gzip -c "./extra/alacritty.man" > "./alacritty.1.gz"
          gzip -c "./extra/alacritty-msg.man" > "./alacritty-msg.1.gz"
      - name: Rename files
        run: |
          mv ./extra/logo/alacritty-term.svg ./Alacritty.svg
      - uses: svenstaro/upload-release-action@v2
        name: Upload attachment to release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: *lacritty.*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
